name: Run final.py every 3 hours

on:
  push:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:       # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 170  # 3 hours

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      M_TOKEN: ${{ secrets.M_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install telethon pymongo tqdm m3u8 pycryptodome requests nest_asyncio aiohttp mega.py


      - name: Run Python script
        run: python final.py
